project:
  type: website

website:
  title: "Residency"
  page-navigation: true
  page-footer:
      center: 
        - text: "Last updated: {{< now >}}"
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: envelope
        menu:
          - text: Email Prof. Fink
            href: mailto:efink@elon.edu
      - icon: calendar
        menu:
          - text: Make an appointment
            href: https://calendly.com/emfink/
      - icon: file-pdf
        menu: 
          - text: "Syllabus PDF"
            href: .pdf/ResidencySyllabus.pdf
      - icon: github
        menu:
          - text: Report an issue
            href:  https://github.com/EricMFink/Residency/issues/new
          - text: View source code
            href:  https://github.com/EricMFink/Residency
    collapse-level: 1
    contents:
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Weekly Reports"
        href: reports.qmd
      - section: "Orientation Materials"
        contents:
          - text: NC Rules of Professional Conduct
            href: materials/NCRPC.pdf
          - text: Neil Hamilton, "Roadmap"
            href: materials/HamiltonRoadmap.pdf
          - text: Doe v. UNC System
            href: materials/DoeUNC-Order-10Nov2025.pdf
          - text: Leadership Skills for Attorney Success
            href: materials/LeadershipSkillsForAttorneySuccess.pdf

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: false
    callout-icon: false
    include-in-header:
    - text: |
        <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Literata:ital,opsz,wght@0,7..72,200..900;1,7..72,200..900&family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="https://www.emfink.net/assets/img/favicon.ico">
        <meta name="robots" content="noarchive">